import NavierStokes.CounterProof.Certificates.ResidualExposure

/-!
# Observable dynamical mismatch

This module formalizes the exact algebraic bridge from a residual-perturbed
state equation to the observed mismatch in the general research note.  The
source-specific chain rule and state equation are explicit fields, so a
concrete adapter cannot silently replace the physical state or observation.
-/

noncomputable section

namespace NavierStokes.CounterProof

variable {State Obs Residual : Type*}
  [NormedAddCommGroup State] [NormedSpace ℝ State]
  [NormedAddCommGroup Obs] [NormedSpace ℝ Obs]
  [NormedAddCommGroup Residual] [NormedSpace ℝ Residual]

/-- Pointwise data for a state equation, its observation, and a physical
residual injection. -/
structure DynamicalMismatchData (State Obs Residual : Type*)
    [NormedAddCommGroup State] [NormedSpace ℝ State]
    [NormedAddCommGroup Obs] [NormedSpace ℝ Obs]
    [NormedAddCommGroup Residual] [NormedSpace ℝ Residual] where
  observeDeriv : State →L[ℝ] Obs
  residualInjection : Residual →L[ℝ] State
  stateVelocity : State
  residualFreeDrift : State
  residual : Residual
  observationVelocity : Obs
  observationTimeDrift : Obs
  state_equation :
    stateVelocity = residualFreeDrift + residualInjection residual
  observation_chain_rule :
    observationVelocity = observationTimeDrift + observeDeriv stateVelocity

namespace DynamicalMismatchData

/-- Observed evolution not generated by the residual-free state drift. -/
def mismatch (D : DynamicalMismatchData State Obs Residual) : Obs :=
  D.observationVelocity - D.observationTimeDrift -
    D.observeDeriv D.residualFreeDrift

/-- Exact residual-exposure identity `Δ = DΠ ∘ B applied to r`. -/
theorem mismatch_eq_residual_response
    (D : DynamicalMismatchData State Obs Residual) :
    D.mismatch = (D.observeDeriv.comp D.residualInjection) D.residual := by
  rw [mismatch, D.observation_chain_rule, D.state_equation]
  simp only [map_add, ContinuousLinearMap.comp_apply]
  abel

/-- Operator-norm control of the observed mismatch by the physical residual. -/
theorem norm_mismatch_le
    (D : DynamicalMismatchData State Obs Residual) :
    ‖D.mismatch‖ ≤ ‖D.observeDeriv.comp D.residualInjection‖ * ‖D.residual‖ := by
  rw [D.mismatch_eq_residual_response]
  exact (D.observeDeriv.comp D.residualInjection).le_opNorm D.residual

/-- A detected mismatch and a positive sensitivity bound force a quantitative
physical residual lower bound. -/
theorem residual_norm_lower_bound
    (D : DynamicalMismatchData State Obs Residual)
    {magnitude sensitivity : ℝ}
    (hmagnitude : magnitude ≤ ‖D.mismatch‖)
    (hsensitivity : ‖D.observeDeriv.comp D.residualInjection‖ ≤ sensitivity)
    (hsensitivity_pos : 0 < sensitivity) :
    magnitude / sensitivity ≤ ‖D.residual‖ := by
  apply (div_le_iff₀ hsensitivity_pos).2
  calc
    magnitude ≤ ‖D.mismatch‖ := hmagnitude
    _ ≤ ‖D.observeDeriv.comp D.residualInjection‖ * ‖D.residual‖ :=
      D.norm_mismatch_le
    _ ≤ sensitivity * ‖D.residual‖ :=
      mul_le_mul_of_nonneg_right hsensitivity (norm_nonneg _)
    _ = ‖D.residual‖ * sensitivity := mul_comm _ _

end DynamicalMismatchData

/-- Forward residual-leakage theorem for a scale-indexed family.  A physical
residual flat to all orders produces an observed mismatch flat to all orders
whenever the exact residual response has a fixed polynomial sensitivity loss.

This is the direct Lean form of Proposition `prop:residualleakage` in §8.2 of
`docs/Primitive_Liftability_Obstructions_NSE_Research_Note.tex`; collecting a
finite residual jet into `Residual` gives the note's Corollary
`cor:jetleakage`. -/
theorem dynamical_mismatch_flat_of_residual_flat
    (data : ℝ → DynamicalMismatchData State Obs Residual)
    {C radius : ℝ} {M : ℕ}
    (hC : 0 ≤ C) (hradius : 0 < radius)
    (hsensitivity : ∀ q, 0 < q → q < radius →
      ‖(data q).observeDeriv.comp (data q).residualInjection‖ ≤ C / q ^ M)
    (hflat : FlatAtZero (fun q => ‖(data q).residual‖)) :
    FlatAtZero (fun q => ‖(data q).mismatch‖) := by
  apply flatAtZero_mismatch_of_polynomial_sensitivity (C := C) (radius := radius) (M := M)
    (fun q => ‖(data q).residual‖) (fun q => ‖(data q).mismatch‖)
    hC hradius _ hflat
  intro q hq hqradius
  calc
    ‖(data q).mismatch‖ ≤
        ‖(data q).observeDeriv.comp (data q).residualInjection‖ *
          ‖(data q).residual‖ :=
      (data q).norm_mismatch_le
    _ ≤ (C / q ^ M) * ‖(data q).residual‖ :=
      mul_le_mul_of_nonneg_right (hsensitivity q hq hqradius) (norm_nonneg _)

/-- A family of exact mismatch identities with polynomial sensitivity and an
algebraic mismatch lower bound forces nonflatness of the physical residual. -/
theorem dynamical_mismatch_forces_nonflat_residual
    (data : ℝ → DynamicalMismatchData State Obs Residual)
    {c C radius : ℝ} {α M : ℕ}
    (hc : 0 < c) (hC : 0 < C) (hradius : 0 < radius)
    (hmismatch : ∀ q, 0 < q → q < radius →
      c * q ^ α ≤ ‖(data q).mismatch‖)
    (hsensitivity : ∀ q, 0 < q → q < radius →
      ‖(data q).observeDeriv.comp (data q).residualInjection‖ ≤ C / q ^ M) :
    ¬ FlatAtZero (fun q => ‖(data q).residual‖) := by
  let coefficient : ℝ := c / C
  have hcoefficient : 0 < coefficient := div_pos hc hC
  apply (AlgebraicLowerBound.mk coefficient (α + M) radius
    hcoefficient hradius ?_).not_flat
  intro q hq hqradius
  have hqpow : 0 < q ^ M := pow_pos hq M
  have hsensitivity_pos : 0 < C / q ^ M := div_pos hC hqpow
  have hlower := (data q).residual_norm_lower_bound
    (hmismatch q hq hqradius) (hsensitivity q hq hqradius) hsensitivity_pos
  have heq : (c * q ^ α) / (C / q ^ M) = coefficient * q ^ (α + M) := by
    dsimp [coefficient]
    field_simp [hq.ne', hC.ne']
    ring
  rwa [heq] at hlower

end NavierStokes.CounterProof
